[package]
name = "test_function_code"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
windows-service = "0.8.0"
tokio = { version = "1.48.0", features = ["full"] }
